name: Build image

on:
  push:
    branches:
      - 'master'
    path:
      - 'go.mod'
      - 'main.go'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build binary
        env:
          CGO_ENABLED: 0
        run: go build -o bin/redirect .

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          image: go-redirect
          tags: ${{ github.sha }} latest
        id: image

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.image.outputs.image }}
          tags: ${{ steps.image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
